module.exports = {
  NEWS_REQUESTED: 'NEWS_REQUESTED',
  NEWS_RECEIVED: 'NEWS_RECEIVED',
  NEWS_FAILED: 'NEWS_FAILED',

  LOGIN_REQUESTED: 'LOGIN_REQUESTED',
  LOGIN_RECEIVED: 'LOGIN_RECEIVED',

  SIGNUP_REQUESTED: 'SIGNUP_REQUESTED',
  SIGNUP_RECEIVED: 'SIGNUP_RECEIVED',

  LOGOUT_REQUESTED: 'REQUESTED_LOGOUT',

  REQUEST_FAILED: 'REQUEST_FAILED',
};
