module.exports = {
  NEWS_REQUESTED: 'NEWS_REQUESTED',
  NEWS_RECEIVED: 'NEWS_RECEIVED',
  NEWS_FAILED: 'NEWS_FAILED',

  LOGIN_REQUESTED: 'LOGIN_REQUESTED',
  LOGIN_RECEIVED: 'LOGIN_RECEIVED',
  REQUEST_LOGIN_FAILED: 'REQUEST_LOGIN_FAILED',

  SIGNUP_REQUESTED: 'SIGNUP_REQUESTED',
  SIGNUP_RECEIVED: 'SIGNUP_RECEIVED',
  REQUEST_SIGNUP_FAILED: 'REQUEST_SIGNUP_FAILED',

  LOGOUT_REQUESTED: 'REQUESTED_LOGOUT',

  REQUEST_FAILED: 'REQUEST_FAILED',

  USER_DATA_REQUEST: 'USER_DATA_REQUEST',
  USER_DATA_RECEIVED: 'USER_DATA_RECEIVED',
  USER_DATA_FAILED: 'USER_DATA_FAILED',

  REQUEST_VERIFY_USER: 'REQUEST_VERIFY_USER',
  REQUEST_VERIFY_USER_FAILED: 'REQUEST_VERIFY_USER_FAILED',
};
